apiVersion: v1
kind: Service
metadata:
  name: nodejsapp02
spec:
  selector:
    app: nodejsapp
  type: LoadBalancer
  loadBalancerIP: 10.10.37.248
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
